import { HudPreset } from '../types';

export const HUD_PRESETS: HudPreset[] = [
  {
    id: 'romance',
    name: 'Romance & Beziehung',
    category: 'Romance',
    description: 'Verfolge Zuneigung, Stimmung, Vertrauen und Beziehungsintensität.',
    icon: 'Heart',
    color: 'from-accent2-500 to-rose-600',
    defaultVariables: [
      { name: 'Affection', value: '50', var_type: 'progress', max_value: 100 },
      { name: 'Mood', value: 'Glücklich', var_type: 'str' },
      { name: 'Trust', value: '65', var_type: 'progress', max_value: 100 },
      { name: 'Intimacy', value: '3', var_type: 'int', max_value: 10 },
    ],
  },
  {
    id: 'rpg_adventure',
    name: 'Fantasy RPG Abenteuer',
    category: 'RPG',
    description: 'Klassische Rollenspiel-Werte wie Lebenspunkte, Mana, Gold und Quest-Status.',
    icon: 'Shield',
    color: 'from-amber-500 to-orange-600',
    defaultVariables: [
      { name: 'HP', value: '95', var_type: 'progress', max_value: 100 },
      { name: 'MP', value: '70', var_type: 'progress', max_value: 80 },
      { name: 'Gold', value: '240', var_type: 'int' },
      { name: 'Level', value: '5', var_type: 'int' },
      { name: 'Quest', value: 'Goblin-Höhle erforschen', var_type: 'str' },
    ],
  },
  {
    id: 'survival',
    name: 'Survival & Post-Apocalypse',
    category: 'Survival',
    description: 'Überlebenswerte: Hunger, Durst, Ausdauer und Infektionsrisiko.',
    icon: 'Compass',
    color: 'from-emerald-500 to-green-700',
    defaultVariables: [
      { name: 'Hunger', value: '40', var_type: 'progress', max_value: 100 },
      { name: 'Durst', value: '60', var_type: 'progress', max_value: 100 },
      { name: 'Ausdauer', value: '85', var_type: 'progress', max_value: 100 },
      { name: 'Infektion', value: '5', var_type: 'progress', max_value: 100 },
      { name: 'Tag', value: '12', var_type: 'int' },
    ],
  },
  {
    id: 'horror',
    name: 'Horror & Mystery',
    category: 'Horror',
    description: 'Psychologischer Horror mit Geistiger Gesundheit, Angstlevel und Herzfrequenz.',
    icon: 'Ghost',
    color: 'from-accent-600 to-indigo-900',
    defaultVariables: [
      { name: 'Sanity', value: '80', var_type: 'progress', max_value: 100 },
      { name: 'Angst', value: '25', var_type: 'progress', max_value: 100 },
      { name: 'Taschenlampe', value: '70', var_type: 'progress', max_value: 100 },
      { name: 'Puls', value: '88', var_type: 'int' },
    ],
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk & Dystopia',
    category: 'Sci-Fi',
    description: 'Cyberware-Belastung, RAM-Decks, Heat-Level und Credits in Night City.',
    icon: 'Cpu',
    color: 'from-cyan-500 to-blue-600',
    defaultVariables: [
      { name: 'Cyber-Strain', value: '30', var_type: 'progress', max_value: 100 },
      { name: 'Cyberdeck RAM', value: '28', var_type: 'progress', max_value: 32 },
      { name: 'Heat Level', value: '1', var_type: 'int', max_value: 5 },
      { name: 'Eddies', value: '1250', var_type: 'int' },
      { name: 'Street Cred', value: '14', var_type: 'int', max_value: 50 },
    ],
  },
  {
    id: 'slice_of_life',
    name: 'Slice of Life & Schule',
    category: 'Casual',
    description: 'Alltags-Drama mit Stress, Energie, Freundschaften und Noten.',
    icon: 'Coffee',
    color: 'from-teal-500 to-emerald-600',
    defaultVariables: [
      { name: 'Stress', value: '35', var_type: 'progress', max_value: 100 },
      { name: 'Energie', value: '80', var_type: 'progress', max_value: 100 },
      { name: 'Freundschaft', value: '75', var_type: 'progress', max_value: 100 },
      { name: 'Notenschnitt', value: 'Gut (2+)', var_type: 'str' },
      { name: 'Klub-Rang', value: '6', var_type: 'int', max_value: 10 },
    ],
  },
  {
    id: 'detective',
    name: 'Detektiv & Ermittlung',
    category: 'Mystery',
    description: 'Verdachtsstufen, gefundene Beweise, Deduktion und Alibis.',
    icon: 'Search',
    color: 'from-yellow-600 to-stone-700',
    defaultVariables: [
      { name: 'Verdacht', value: '20', var_type: 'progress', max_value: 100 },
      { name: 'Hinweise', value: '4', var_type: 'int', max_value: 12 },
      { name: 'Deduktion', value: '85', var_type: 'progress', max_value: 100 },
      { name: 'Alibi', value: 'Fragwürdig', var_type: 'str' },
    ],
  },
  {
    id: 'space_opera',
    name: 'Sci-Fi & Weltraum',
    category: 'Sci-Fi',
    description: 'Schilde, Hülle, Treibstoff, Sauerstoff und Reaktorstatus deines Raumschiffs.',
    icon: 'Rocket',
    color: 'from-indigo-500 to-sky-700',
    defaultVariables: [
      { name: 'Schilde', value: '100', var_type: 'progress', max_value: 100 },
      { name: 'Hülle', value: '90', var_type: 'progress', max_value: 100 },
      { name: 'Treibstoff', value: '65', var_type: 'progress', max_value: 100 },
      { name: 'Sauerstoff', value: '95', var_type: 'progress', max_value: 100 },
      { name: 'Warpkern', value: 'Stabil', var_type: 'str' },
    ],
  },
  {
    id: 'cultivation',
    name: 'Cultivation & Wuxia',
    category: 'Fantasy',
    description: 'Qi im Dantian, Kultivierungsreich, Karma und himmlische Trübsale.',
    icon: 'Flame',
    color: 'from-red-600 to-amber-700',
    defaultVariables: [
      { name: 'Dantian Qi', value: '420', var_type: 'progress', max_value: 1000 },
      { name: 'Reich', value: 'Fundament-Errichtung', var_type: 'str' },
      { name: 'Karma', value: '15', var_type: 'int' },
      { name: 'Trübsal-Nähe', value: '10', var_type: 'progress', max_value: 100 },
    ],
  },
  {
    id: 'comedy',
    name: 'Comedy & Slapstick',
    category: 'Casual',
    description: 'Spaß-Barometer, Chaos-Grad, Glück und die allgemeine Stimmung.',
    icon: 'Sparkles',
    color: 'from-fuchsia-500 to-accent2-600',
    defaultVariables: [
      { name: 'Spaß-Faktor', value: '90', var_type: 'progress', max_value: 100 },
      { name: 'Chaos-Level', value: '4', var_type: 'int', max_value: 10 },
      { name: 'Glück', value: '77', var_type: 'int', max_value: 100 },
      { name: 'Vibe', value: 'Total aufgedreht', var_type: 'str' },
    ],
  },
  {
    id: 'tabletop_tactical',
    name: 'Tabletop Taktik (D&D/OSR)',
    category: 'RPG',
    description: 'Rüstungsklasse, Trefferwürfel, Zauberplätze, Inspiration und Initiative.',
    icon: 'Dice5',
    color: 'from-violet-600 to-accent-800',
    defaultVariables: [
      { name: 'Rüstungsklasse (AC)', value: '16', var_type: 'int' },
      { name: 'Trefferwürfel', value: '4d8', var_type: 'str' },
      { name: 'Zauberplätze', value: '4/3/1', var_type: 'str' },
      { name: 'Inspiration', value: 'true', var_type: 'bool' },
      { name: 'Initiative', value: '14', var_type: 'int' },
    ],
  },
];
