// NPC lifecycle through the UI, with private memory and V2 promotion verified through IPC.
import assert from 'node:assert/strict';
import path from 'node:path';
import { launch, screenshotDir } from './harness.mjs';

const { browser, mock, close } = await launch();
// oxlint-disable-next-line no-underscore-dangle -- Tauri-IPC im Wegwerfprofil
const invoke = (command, args = {}) => browser.execute((cmd, payload) => window.__TAURI_INTERNALS__.invoke(cmd, payload), command, args);
const shot = (name) => browser.saveScreenshot(path.join(screenshotDir, `${name}.png`));
try {
  await browser.$('button=Soul Stage').waitForExist({ timeout: 20_000 });
  await browser.$('button=Soul Stage').click();
  // The selector below does not depend on the exact translated input label.
  const stageInput = await browser.$('form textarea');
  await stageInput.waitForDisplayed({ timeout: 15_000 });
  const initial = await invoke('get_stage_state');
  initial.chat_log.push({ ...initial.chat_log[0], id: 'before-arrival', content: 'BEFORE_ARRIVAL_SECRET', turn_mode: 'say' });
  await invoke('save_stage_scene', { sceneState: initial });
  const openNpcs = async () => {
    await browser.$('button*=NPCs (').click();
    await browser.$('#stage-npc-title').waitForDisplayed();
  };
  const closeNpcs = () => browser.$('[role="dialog"] button[aria-label="Schließen"]').click();
  await openNpcs();
  await browser.$('[role="dialog"] input').setValue('Liora');
  await browser.$('[role="dialog"] select').selectByAttribute('value', 'merchant');
  await browser.$('[role="dialog"] textarea').setValue('Eine aufmerksame Händlerin, die Versprechen ernst nimmt.');
  await browser.$('button=NPC speichern / erscheinen lassen').click();
  await browser.$('h3=Liora').waitForExist();
  await shot('13-npc-verwaltung');
  await closeNpcs();
  const send = async (text) => {
    const before = mock.stats.stageNarrator;
    await stageInput.setValue(text);
    await browser.keys('Enter');
    await browser.waitUntil(() => mock.stats.stageNarrator > before, { timeout: 20_000 });
    await browser.$('button=Stopp').waitForExist({ reverse: true, timeout: 30_000 });
  };
  await browser.$('button=Flüstern').click();
  await browser.$('select[aria-label^="Ziel"]').selectByAttribute('value', 'Liora');
  await send('Das Geheimwort lautet Saphirschlüssel.');
  assert.ok(mock.stats.stageNpc > 0, 'NPC spricht nicht');
  assert.ok(JSON.stringify(mock.stats.lastNpcMessages).includes('Saphirschlüssel'), 'NPC kennt eigenes Flüstern nicht');
  assert.ok(!JSON.stringify(mock.stats.lastNpcMessages).includes('BEFORE_ARRIVAL_SECRET'), 'NPC kennt Geschehnisse vor seiner Ankunft');
  assert.ok(!JSON.stringify(mock.stats.lastNarratorMessages).includes('Saphirschlüssel'), 'NPC-Flüstern ist nicht privat');
  await shot('14-npc-dialog');
  const first = await invoke('get_stage_state');
  const npc = first.npcs.find((n) => n.name === 'Liora');
  assert.ok(npc.memories.some((m) => m.text.includes('Saphirschlüssel')));
  assert.ok(first.chat_log.some((m) => m.sender_role === 'npc' && m.avatar_url?.startsWith('data:image/png;base64,')));
  await openNpcs();
  await browser.$('button=Szene verlassen').click();
  await browser.$('p*=Abwesend').waitForExist();
  await closeNpcs();
  await browser.$('button=Sagen').click();
  await send('ABSENT_NPC_SECRET');
  await openNpcs();
  await browser.$('button=Zurückholen').click();
  await browser.$('p*=Anwesend').waitForExist();
  await closeNpcs();
  await browser.$('button=Flüstern').click();
  await browser.$('select[aria-label^="Ziel"]').selectByAttribute('value', 'Liora');
  await send('Erinnerst du dich an den Saphirschlüssel?');
  assert.ok(!JSON.stringify(mock.stats.lastNpcMessages).includes('ABSENT_NPC_SECRET'), 'NPC weiß von Ereignissen während seiner Abwesenheit');
  const returned = await invoke('get_stage_state');
  assert.equal(returned.npcs[0].id, npc.id, 'Rückkehr ersetzt NPC-Identität');
  assert.ok(returned.npcs[0].turn_count >= 2);
  const reloaded = await invoke('load_stage_scene', { sceneId: initial.definition.id });
  assert.deepEqual(reloaded.npcs, returned.npcs);
  await openNpcs();
  await browser.$('button=Zum Charakter befördern').click();
  await browser.$('p*=Als Charakter in der Party').waitForExist({ timeout: 15_000 });
  await shot('15-npc-befoerdert');
  const promoted = await invoke('get_stage_state');
  const id = promoted.npcs[0].promoted_character_id;
  assert.ok(id);
  assert.ok(promoted.definition.party.includes('Liora'));
  const characters = await invoke('scan_characters');
  const character = characters.find((c) => c.id === id);
  assert.equal(character.card.spec, 'chara_card_v2');
  assert.equal(character.card.data.name, 'Liora');
  assert.ok(character.avatar_data_url.startsWith('data:image/png;base64,'));
  const memory = await invoke('get_cognitive_overview', { charId: id, userName: 'Kai' });
  assert.ok(memory.recent_memories.some((m) => m.content.includes('Saphirschlüssel')), 'Soul Memory wurde nicht übernommen');
  assert.ok(!memory.recent_memories.some((m) => m.content.includes('ABSENT_NPC_SECRET')));
  const retry = await invoke('stage_promote_npc', { sceneId: initial.definition.id, npcId: npc.id });
  assert.equal(retry.character.id, id, 'Befördern ist nicht idempotent');
  const retryMemory = await invoke('get_cognitive_overview', { charId: id, userName: 'Kai' });
  assert.equal(retryMemory.recent_memories.length, memory.recent_memories.length);
  await closeNpcs();
  await browser.$('select[aria-label="Nächster Sprecher"]').selectByAttribute('value', 'Liora');
  await browser.$('button=Sagen').click();
  await send('Wir sprechen über den Saphirschlüssel.');
  assert.ok(mock.stats.companionMessagesByName?.Liora, 'Beförderter NPC reagiert nicht als Charakter');
  assert.ok(!JSON.stringify(mock.stats.companionMessagesByName.Liora).includes('ABSENT_NPC_SECRET'), 'Beförderter NPC erfährt nachträglich fremde Ereignisse');
  await browser.$('select[aria-label="Nächster Sprecher"]').selectByAttribute('value', '');
  mock.stats.spawnNpc = { name: 'Tarek', archetype: 'guard', personality: 'Eine pflichtbewusste Torwache.' };
  await browser.$('button=Sagen').click();
  await send('Am Tor begegnen wir einer Wache.');
  mock.stats.spawnNpc = null;
  const spawned = await invoke('get_stage_state');
  assert.ok(spawned.npcs.some((n) => n.name === 'Tarek' && n.active));
  assert.ok(spawned.chat_log.some((m) => m.sender_role === 'npc' && m.sender_name === 'Tarek'));
  await shot('16-npc-spielleiter');
  mock.stats.despawnNpc = 'Tarek';
  await send('Die Wache geht weiter.');
  mock.stats.despawnNpc = null;
  const dismissed = await invoke('get_stage_state');
  assert.ok(dismissed.npcs.some((n) => n.name === 'Tarek' && !n.active && n.memories.length > 0));
  await browser.setWindowSize(960, 640);
  await openNpcs();
  await shot('18-npc-mindestgroesse');
  await closeNpcs();
  await browser.setWindowSize(1280, 840);
  await browser.$('button=Charaktere').click();
  const search = await browser.$('input[aria-label="Charaktere durchsuchen"]');
  await search.waitForDisplayed({ timeout: 15_000 });
  await search.setValue('Liora');
  await browser.$('img[alt="Liora"]').waitForDisplayed({ timeout: 15_000 });
  await shot('17-npc-charakterbibliothek');
  console.log('✔ NPC-System bestanden (Dialog, Geheimhaltung, Rückkehr, Spielleiter und Beförderung samt Soul Memory)');
} catch (error) {
  await shot('npc-fehler').catch(() => {});
  throw error;
} finally {
  await close();
}
