/**
 * Compile-time check that the hand-written types in ./index.ts use the same field names as the
 * Rust types they mirror (generated by ts-rs into ./generated). `tsc` fails with the offending
 * field names when a field is added, removed or renamed on either side.
 *
 * Field *types* may deliberately be narrower in the frontend (e.g. `'local' | 'cloud'` instead of
 * `string`), so only names are compared. Intentional differences are listed per type.
 */
import type * as Frontend from './index';

import type { LlamaServerConfig as RustLlamaServerConfig } from './generated/LlamaServerConfig';
import type { ChatMessage as RustChatMessage } from './generated/ChatMessage';
import type { SamplingParams as RustSamplingParams } from './generated/SamplingParams';
import type { ChatRequest as RustChatRequest } from './generated/ChatRequest';
import type { CharacterData as RustCharacterData } from './generated/CharacterData';
import type { CharacterCardV2 as RustCharacterCardV2 } from './generated/CharacterCardV2';
import type { CharacterProfile as RustCharacterProfile } from './generated/CharacterProfile';
import type { LorebookEntry as RustLorebookEntry } from './generated/LorebookEntry';
import type { Lorebook as RustLorebook } from './generated/Lorebook';
import type { EvaluatedLoreResult as RustEvaluatedLoreResult } from './generated/EvaluatedLoreResult';
import type { StateVariable as RustStateVariable } from './generated/StateVariable';
import type { PsychologyState as RustPsychologyState } from './generated/PsychologyState';
import type { RelationshipState as RustRelationshipState } from './generated/RelationshipState';
import type { SoulMemoryPipelineRequest as RustSoulMemoryPipelineRequest } from './generated/SoulMemoryPipelineRequest';
import type { SoulMemoryPipelineResult as RustSoulMemoryPipelineResult } from './generated/SoulMemoryPipelineResult';
import type { CognitiveOverview as RustCognitiveOverview } from './generated/CognitiveOverview';
import type { PromptContext as RustPromptContext } from './generated/PromptContext';
import type { DiceRollResult as RustDiceRollResult } from './generated/DiceRollResult';
import type { Combatant as RustCombatant } from './generated/Combatant';
import type { EncounterState as RustEncounterState } from './generated/EncounterState';
import type { ScenePreview as RustScenePreview } from './generated/ScenePreview';
import type { SceneDefinition as RustSceneDefinition } from './generated/SceneDefinition';
import type { InventoryItem as RustInventoryItem } from './generated/InventoryItem';
import type { TaggedChoice as RustTaggedChoice } from './generated/TaggedChoice';
import type { DiceEventData as RustDiceEventData } from './generated/DiceEventData';
import type { ClockUpdateData as RustClockUpdateData } from './generated/ClockUpdateData';
import type { RestEventData as RustRestEventData } from './generated/RestEventData';
import type { SceneTurnMessage as RustSceneTurnMessage } from './generated/SceneTurnMessage';
import type { SceneState as RustSceneState } from './generated/SceneState';
import type { StageTurnRequest as RustStageTurnRequest } from './generated/StageTurnRequest';
import type { Goal as RustGoal } from './generated/Goal';
import type { ToolCallRequest as RustToolCallRequest } from './generated/ToolCallRequest';
import type { CompanionSettings as RustCompanionSettings } from './generated/CompanionSettings';
import type { CompanionState as RustCompanionState } from './generated/CompanionState';
import type { EnvironmentSnapshot as RustEnvironmentSnapshot } from './generated/EnvironmentSnapshot';
import type { McpServerConfig as RustMcpServerConfig } from './generated/McpServerConfig';
import type { McpToolInfo as RustMcpToolInfo } from './generated/McpToolInfo';
import type { CompanionPlugin as RustCompanionPlugin } from './generated/CompanionPlugin';
import type { ScannedModel as RustScannedModel } from './generated/ScannedModel';
import type { AppSettings as RustAppSettings } from './generated/AppSettings';
import type { ScannedLive2d as RustScannedLive2d } from './generated/ScannedLive2d';
import type { EmotionResult as RustEmotionResult } from './generated/EmotionResult';
import type { UserPersona as RustUserPersona } from './generated/UserPersona';
import type { SwipeVariant as RustSwipeVariant } from './generated/SwipeVariant';
import type { StoredChatMessage as RustStoredChatMessage } from './generated/StoredChatMessage';
import type { LlmPreset as RustLlmPreset } from './generated/LlmPreset';
import type { HfModelSummary as RustHfModelSummary } from './generated/HfModelSummary';
import type { HfGgufFile as RustHfGgufFile } from './generated/HfGgufFile';
import type { DownloadProgressEvent as RustDownloadProgressEvent } from './generated/DownloadProgressEvent';
import type { ChubSearchItem as RustChubSearchItem } from './generated/ChubSearchItem';
import type { ChubSearchResult as RustChubSearchResult } from './generated/ChubSearchResult';
import type { CharacterImportResult as RustCharacterImportResult } from './generated/CharacterImportResult';
import type { BackupManifest as RustBackupManifest } from './generated/BackupManifest';
import type { BackupEntryInfo as RustBackupEntryInfo } from './generated/BackupEntryInfo';
import type { ImageGenConfig as RustImageGenConfig } from './generated/ImageGenConfig';
import type { DiscordRpcActivity as RustDiscordRpcActivity } from './generated/DiscordRpcActivity';
import type { DiscordBotStatus as RustDiscordBotStatus } from './generated/DiscordBotStatus';
import type { CharacterWizardInput as RustCharacterWizardInput } from './generated/CharacterWizardInput';
import type { UpdateInfo as RustUpdateInfo } from './generated/UpdateInfo';

/** `true` when both types have the same keys apart from the listed exceptions, else the difference. */
type SameFields<F, R, OnlyFrontend extends PropertyKey = never, OnlyRust extends PropertyKey = never> = [
  Exclude<keyof F, keyof R | OnlyFrontend>,
  Exclude<keyof R, keyof F | OnlyRust>,
] extends [never, never]
  ? true
  : { onlyInFrontend: Exclude<keyof F, keyof R | OnlyFrontend>; onlyInRust: Exclude<keyof R, keyof F | OnlyRust> };

const expectMatch = <T extends true>(): T | undefined => undefined;

expectMatch<SameFields<Frontend.LlamaServerConfig, RustLlamaServerConfig>>();
// thought is shown in the UI but not sent to the model.
expectMatch<SameFields<Frontend.ChatMessage, RustChatMessage, 'thought', never>>();
expectMatch<SameFields<Frontend.SamplingParams, RustSamplingParams>>();
expectMatch<SameFields<Frontend.ChatRequest, RustChatRequest>>();
expectMatch<SameFields<Frontend.CharacterData, RustCharacterData>>();
expectMatch<SameFields<Frontend.CharacterCardV2, RustCharacterCardV2>>();
expectMatch<SameFields<Frontend.CharacterProfile, RustCharacterProfile>>();
expectMatch<SameFields<Frontend.LorebookEntry, RustLorebookEntry>>();
expectMatch<SameFields<Frontend.Lorebook, RustLorebook>>();
expectMatch<SameFields<Frontend.EvaluatedLoreResult, RustEvaluatedLoreResult>>();
expectMatch<SameFields<Frontend.StateVariable, RustStateVariable>>();
expectMatch<SameFields<Frontend.PsychologyState, RustPsychologyState>>();
expectMatch<SameFields<Frontend.RelationshipState, RustRelationshipState>>();
expectMatch<SameFields<Frontend.SoulMemoryPipelineRequest, RustSoulMemoryPipelineRequest>>();
expectMatch<SameFields<Frontend.SoulMemoryPipelineResult, RustSoulMemoryPipelineResult>>();
expectMatch<SameFields<Frontend.CognitiveOverview, RustCognitiveOverview>>();
expectMatch<SameFields<Frontend.PromptContext, RustPromptContext>>();
expectMatch<SameFields<Frontend.DiceRollResult, RustDiceRollResult>>();
expectMatch<SameFields<Frontend.Combatant, RustCombatant>>();
expectMatch<SameFields<Frontend.EncounterState, RustEncounterState>>();
expectMatch<SameFields<Frontend.ScenePreview, RustScenePreview>>();
expectMatch<SameFields<Frontend.SceneDefinition, RustSceneDefinition>>();
expectMatch<SameFields<Frontend.InventoryItem, RustInventoryItem>>();
expectMatch<SameFields<Frontend.TaggedChoice, RustTaggedChoice>>();
// ts-rs puts the event tag on the StageEventCard union instead.
expectMatch<SameFields<Frontend.DiceEventData, RustDiceEventData, 'type', never>>();
// ts-rs puts the event tag on the StageEventCard union instead.
expectMatch<SameFields<Frontend.ClockUpdateData, RustClockUpdateData, 'type', never>>();
// ts-rs puts the event tag on the StageEventCard union instead.
expectMatch<SameFields<Frontend.RestEventData, RustRestEventData, 'type', never>>();
expectMatch<SameFields<Frontend.SceneTurnMessage, RustSceneTurnMessage>>();
expectMatch<SameFields<Frontend.SceneState, RustSceneState>>();
expectMatch<SameFields<Frontend.StageTurnRequest, RustStageTurnRequest>>();
expectMatch<SameFields<Frontend.Goal, RustGoal>>();
expectMatch<SameFields<Frontend.ToolCallRequest, RustToolCallRequest>>();
expectMatch<SameFields<Frontend.CompanionSettings, RustCompanionSettings>>();
expectMatch<SameFields<Frontend.CompanionState, RustCompanionState>>();
expectMatch<SameFields<Frontend.EnvironmentSnapshot, RustEnvironmentSnapshot>>();
expectMatch<SameFields<Frontend.McpServerConfig, RustMcpServerConfig>>();
expectMatch<SameFields<Frontend.McpToolInfo, RustMcpToolInfo>>();
expectMatch<SameFields<Frontend.CompanionPlugin, RustCompanionPlugin>>();
expectMatch<SameFields<Frontend.ScannedModel, RustScannedModel>>();
// hidden_character_ids is managed by the backend only.
expectMatch<SameFields<Frontend.AppSettings, RustAppSettings, never, 'hidden_character_ids'>>();
expectMatch<SameFields<Frontend.ScannedLive2d, RustScannedLive2d>>();
expectMatch<SameFields<Frontend.EmotionResult, RustEmotionResult>>();
expectMatch<SameFields<Frontend.UserPersona, RustUserPersona>>();
expectMatch<SameFields<Frontend.SwipeVariant, RustSwipeVariant>>();
expectMatch<SameFields<Frontend.StoredChatMessage, RustStoredChatMessage>>();
expectMatch<SameFields<Frontend.LlmPreset, RustLlmPreset>>();
expectMatch<SameFields<Frontend.HfModelSummary, RustHfModelSummary>>();
expectMatch<SameFields<Frontend.HfGgufFile, RustHfGgufFile>>();
expectMatch<SameFields<Frontend.DownloadProgressEvent, RustDownloadProgressEvent>>();
expectMatch<SameFields<Frontend.ChubSearchItem, RustChubSearchItem>>();
expectMatch<SameFields<Frontend.ChubSearchResult, RustChubSearchResult>>();
expectMatch<SameFields<Frontend.CharacterImportResult, RustCharacterImportResult>>();
expectMatch<SameFields<Frontend.BackupManifest, RustBackupManifest>>();
expectMatch<SameFields<Frontend.BackupEntryInfo, RustBackupEntryInfo>>();
expectMatch<SameFields<Frontend.ImageGenConfig, RustImageGenConfig>>();
expectMatch<SameFields<Frontend.DiscordRpcActivity, RustDiscordRpcActivity>>();
expectMatch<SameFields<Frontend.DiscordBotStatus, RustDiscordBotStatus>>();
expectMatch<SameFields<Frontend.CharacterWizardInput, RustCharacterWizardInput>>();
expectMatch<SameFields<Frontend.UpdateInfo, RustUpdateInfo>>();

expectMatch<SameFields<Frontend.StageNpcPromotion, import('./generated/StageNpcPromotion').StageNpcPromotion>>();
