// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppPaths = { config_dir: string, data_dir: string, characters_dir: string, lorebooks_dir: string, personas_dir: string, scenes_dir: string, trash_dir: string, bundled_presets_dir: string, bundled_models_dir: string, bundled_vrm_dir: string, bundled_bin_dir: string, };
