// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupManifest } from "./BackupManifest";

export type BackupEntryInfo = { id: string, filename: string, file_path: string, size_bytes: bigint, created_at: string, is_safety_snapshot: boolean, manifest: BackupManifest | null, };
