// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CampaignClock = { id: string, name: string, current: number, max: number, clock_type: string, };
