// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CharacterData = { name: string, description: string, personality: string, scenario: string, first_mes: string, mes_example: string, alternate_greetings: Array<string>, system_prompt: string | null, post_history_instructions: string | null, creator_notes: string | null, character_version: string | null, tags: Array<string>, creator: string | null, character_book: JsonValue | null, extensions: JsonValue, };
