// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterCardV2 } from "./CharacterCardV2";

export type CharacterProfile = { id: string, card: CharacterCardV2, avatar_data_url: string | null, source_path: string | null, bound_lorebooks: Array<string>, };
