// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatSession = { id: string, character_id: string, title: string, created_at: bigint, updated_at: bigint, author_note: string, author_note_depth: number, message_count: number, };
