// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChubCharacterDetail = { name: string, tagline: string, avatar_url: string, star_count: number, n_favorites: number, n_tokens: number, personality: string, first_message: string, scenario: string, example_dialogs: string, alternate_greetings: Array<string>, has_embedded_lorebook: boolean, };
