// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiaryEntry } from "./DiaryEntry";
import type { EpisodicMemory } from "./EpisodicMemory";
import type { HealingLogEntry } from "./HealingLogEntry";
import type { PsychologyState } from "./PsychologyState";
import type { RelationshipState } from "./RelationshipState";

export type CognitiveOverview = { psychology: PsychologyState, relationship: RelationshipState, recent_memories: Array<EpisodicMemory>, recent_diary: Array<DiaryEntry>, healing_logs: Array<HealingLogEntry>, };
