// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CombatCondition } from "./CombatCondition";

export type Combatant = { id: string, name: string, role: string, hp: number, max_hp: number, stress: number, max_stress: number, initiative: number, conditions: Array<CombatCondition>, };
