// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompanionSettings = { auto_approve_safe_tools: boolean, countdown_seconds: number, enable_neurohormones: boolean, proactive_interval_seconds: number, enable_proactive_speaking: boolean, };
