// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiscordRpcActivity = { details: string, state: string, character_name: string | null, start_timestamp: bigint | null, };
