// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiscordBotStatus = { is_running: boolean, bot_user: string | null, connected_guilds: number, uptime_secs: bigint, };
