// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadProgressEvent = { filename: string, downloaded_bytes: bigint, total_bytes: bigint, percent: number, speed_mbps: number, 
/**
 * Estimated seconds until the download completes; `None` while unknown or when finished.
 */
eta_seconds: bigint | null, finished: boolean, error: string | null, };
