// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EmotionResult = { 
/**
 * The primary detected emotion out of the 28 GoEmotions
 */
emotion: string, 
/**
 * Canonical VRM blendshape name: "happy" | "angry" | "sad" | "surprised" | "relaxed" | "neutral"
 */
vrm_expression: string, 
/**
 * Live2D expression animation key (e.g. "joy_animation", "admiration_animation")
 */
live2d_expression: string, 
/**
 * Confidence score between 0.0 and 1.0
 */
confidence: number, 
/**
 * Intensity between 0.0 and 1.0
 */
intensity: number, };
