// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 10 distinct affective states mapped via Exponential Moving Average (EMA)
 */
export type EmotionState = { current: string, last_updated: bigint, ema_scores: { [key in string]: number }, history: Array<[string, bigint]>, };
