// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * System snapshot of CPU, RAM, Disk, GPU and Battery.
 */
export type EnvironmentSnapshot = { cpu_usage_percent: number, ram_used_mb: bigint, ram_total_mb: bigint, ram_percent: number, disk_free_gb: number, disk_total_gb: number, disk_percent: number, battery_percent: number | null, battery_charging: boolean | null, gpu_name: string | null, gpu_temp_c: number | null, gpu_util_percent: number | null, gpu_vram_used_mb: bigint | null, gpu_vram_total_mb: bigint | null, uptime_seconds: bigint, active_processes_count: number, };
