// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EpisodicMemory = { id: bigint, category: string, content: string, significance: number, created_at: bigint, last_accessed_at: bigint, };
