// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneratedImageInfo = { file_name: string, file_path: string, size_bytes: bigint, created_at: string, };
