// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuInfo } from "./GpuInfo";

export type HardwareInfo = { os_name: string, os_version: string, cpu_name: string, cpu_cores: number, total_ram_mb: bigint, available_ram_mb: bigint, gpus: Array<GpuInfo>, };
