// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HfModelSummary = { id: string, author: string, downloads: bigint, likes: bigint, pipeline_tag: string | null, last_modified: string | null, };
