// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageGenConfig = { provider: string, api_url: string, api_key: string | null, positive_prompt_prefix: string, negative_prompt: string, width: number, height: number, steps: number, cfg_scale: number, sampler_name: string, seed: bigint, };
