// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScannedVoice } from "./ScannedVoice";

export type KokoroInstallResult = { model_path: string, voices_path: string, installed_voices: Array<ScannedVoice>, };
