// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KokoroDownloadProgress = { filename: string, file_index: number, total_files: number, downloaded_bytes: bigint, total_bytes: bigint, percent: number, finished: boolean, };
