// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LayerRecommendation = { recommended_layers: number, recommended_context_size: number, fits_entirely_in_vram: boolean, estimated_vram_usage_mb: bigint, available_vram_mb: bigint, estimated_model_vram_mb: bigint, estimated_context_vram_mb: bigint, runtime_overhead_mb: bigint, profile_name: string, advice: string, };
