// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Live2dCatalogItem = { id: string, name: string, description: string, url: string, model_file: string, is_installed: boolean, };
