// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LlamaRuntimeProgress = { 
/**
 * `download`, `extract` or `done`.
 */
phase: string, downloaded_bytes: bigint, total_bytes: bigint, percent: number, finished: boolean, };
