// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One downloadable build for this system, e.g. `vulkan` or `cuda-12.8`.
 */
export type LlamaRuntimeVariant = { 
/**
 * Backend name from the asset, also used to install it (`cpu`, `vulkan`, `cuda-12.8`, …).
 */
backend: string, build: string, download_bytes: bigint, 
/**
 * Best match for the detected GPU.
 */
recommended: boolean, };
