// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LlmProviderType = "local_llama" | "open_router" | "anthropic" | "open_ai" | "deep_seek" | "gemini" | "mistral" | "custom";
