// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LorebookEntry } from "./LorebookEntry";

export type Lorebook = { id: string, name: string, description: string, scan_depth: number, is_global: boolean, file_path: string | null, entries: Array<LorebookEntry>, };
