// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpServerConfig = { id: string, name: string, transport: string, command: string | null, args: Array<string> | null, env: { [key in string]: string } | null, url: string | null, enabled: boolean, };
