// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiaryEntry } from "./DiaryEntry";
import type { EpisodicMemory } from "./EpisodicMemory";
import type { HealingLogEntry } from "./HealingLogEntry";
import type { PsychologyState } from "./PsychologyState";
import type { RelationshipState } from "./RelationshipState";

export type MemoryBackupSnapshot = { character_id: string, created_at: bigint, psychology: PsychologyState, relationship: RelationshipState | null, episodic_memories: Array<EpisodicMemory>, diary_entries: Array<DiaryEntry>, healing_logs: Array<HealingLogEntry>, };
