// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Neurohormones = { dopamine: number, cortisol: number, oxytocin: number, fatigue: number, mood_label: string, energy_level: number, };
