// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpenRouterModelInfo = { id: string, name: string, context_length: bigint | null, prompt_pricing: string | null, completion_pricing: string | null, };
