// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanCombatDelta } from "./PlanCombatDelta";
import type { PlanCombatant } from "./PlanCombatant";

export type PlanEncounterUpdate = { action: string, enemies: Array<PlanCombatant>, hp_updates: Array<PlanCombatDelta>, };
