// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanInventoryAdd = { name: string, description: string, quantity: number, item_type: string, hp_restore: number, stress_restore: number, clears_condition: string | null, };
