// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RestEventData = { rest_type: string, recovered_hp: number, recovered_stress: number, campfire_note: string, };
