// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RouterRelationshipMetadataPatch = { trust_level: string | null, dynamic_description: string | null, unspoken_tension: string | null, };
