// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RouterInternalStatePatch = { primary_emotion: string | null, intensity: number | null, psychological_tension: string | null, emotion_active: boolean | null, };
