// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScannedLive2d = { id: string, name: string, model_path: string, preview_image: string | null, version: string, };
