// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerState } from "./ServerState";

export type ServerStatus = { state: ServerState, port: number, pid: number | null, model_name: string | null, error_message: string | null, recent_logs: Array<string>, };
