// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LlmProviderType } from "./LlmProviderType";

export type SoulMemoryPipelineRequest = { character_id: string, user_name: string, chat_id: string | null, endpoint_url: string, api_key: string | null, model: string | null, provider: LlmProviderType | null, recent_turn_count: number | null, include_diary: boolean | null, };
