// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StageTurnRequest = { scene_id: string, user_input: string, turn_mode: string, whisper_target: string | null, force_next_actor: string | null, };
