// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StageRelationship = { subject: string, target: string, affinity: number, tags: Array<string>, role_view: string, last_shift_reason: string, };
