// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClockUpdateData } from "./ClockUpdateData";
import type { DiceEventData } from "./DiceEventData";
import type { RestEventData } from "./RestEventData";

export type StageEventCard = { "type": "dice_roll" } & DiceEventData | { "type": "clock_update" } & ClockUpdateData | { "type": "rest" } & RestEventData | { "type": "discovery", text: string, } | { "type": "consequence", text: string, } | { "type": "item_use", item_name: string, hp_recovered: number, stress_recovered: number, cleared_condition: string | null, } | { "type": "bond_milestone", companion: string, affinity: number, milestone: number, } | { "type": "combat", action: string, text: string, };
