// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StoryArc = { id: string, title: string, description: string, stage: number, max_stage: number, is_revealed: boolean, is_resolved: boolean, };
