// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SwipeVariant } from "./SwipeVariant";

export type StoredChatMessage = { id: string, chat_id: string, role: string, content: string, thought: string | null, order_index: number, swipe_index: number, swipes: Array<SwipeVariant>, created_at: bigint, };
