// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ToolCallRequest = { id: string, tool_name: string, arguments: JsonValue, requires_confirmation: boolean, status: string, created_at: bigint, };
