// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebServerConfig = { enabled: boolean, port: number, host: string, auth_token: string, };
