pub mod attachments;
pub mod characters;
pub mod chat_summary;
pub mod companion;
pub mod companion_tools;
pub mod content_lang;
pub mod context_window;
pub mod discord;
pub mod emotions;
pub mod error;
pub mod gguf;
pub mod hardware;
pub mod hub;
pub mod image_generator;
pub mod inference;
pub mod kokoro;
pub mod live2d;
pub mod llama_manager;
pub mod llm_presets;
pub mod local_image;
pub mod logger;
pub mod lorebook;
pub mod mcp_client;
pub mod memory;
pub mod memory_pipeline;
pub mod model_files;
pub mod models_hub;
pub mod paths;
pub mod profile_backup;
pub mod prompt_builder;
pub mod providers;
pub mod runtimes;
pub mod secrets;
pub mod settings;
pub mod stage;
pub use hub as soul_hub;
pub use memory_pipeline as soul_memory_pipeline;
pub mod translate;
pub mod tts_local;
pub mod updater;
pub mod voice;
pub mod web_server;

pub const APP_NAME: &str = "OtakuSoul";
pub const APP_DEFAULT_COMPANION_NAME: &str = "Companion";
