pub mod commands;
pub mod modules;
pub mod state;

use state::AppState;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Initialize tracing subscriber for clean logs
    let _ = tracing_subscriber::fmt().try_init();

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .manage(AppState::new())
        .invoke_handler(tauri::generate_handler![
            commands::get_hardware_info,
            commands::get_layer_recommendation,
            commands::start_llama_server,
            commands::stop_llama_server,
            commands::get_llama_server_status,
            commands::send_chat_message,
            commands::abort_chat_generation,
            commands::load_character_card,
            commands::load_lorebook,
            commands::list_all_lorebooks,
            commands::save_lorebook,
            commands::delete_lorebook,
            commands::import_lorebook_file,
            commands::export_lorebook_file,
            commands::evaluate_lorebook_context,
            commands::evaluate_multi_lorebooks,
            commands::assemble_prompt,
            commands::read_file_binary,
            commands::get_cognitive_overview,
            commands::update_psychology,
            commands::update_relationship,
            commands::add_episodic_memory,
            commands::add_diary_entry,
            commands::apply_emotional_decay,
            commands::trigger_memory_pipeline,
            commands::get_character_memory_markdown,
            commands::save_character_memory_markdown,
            commands::get_user_memory_markdown,
            commands::save_user_memory_markdown,
            commands::generate_manual_diary_entry,
            commands::import_sow_memory_files,
            commands::backup_memory_state,
            commands::list_memory_backups,
            commands::restore_memory_backup,
            commands::roll_stage_dice,
            commands::get_stage_state,
            commands::update_world_state,
            commands::set_clock_progress,
            commands::add_clock,
            commands::delete_clock,
            commands::start_encounter,
            commands::end_encounter,
            commands::next_encounter_turn,
            commands::apply_combatant_delta,
            commands::add_combatant_condition,
            commands::get_companion_state,
            commands::apply_hormone_interaction,
            commands::set_hormones,
            commands::request_tool_call,
            commands::resolve_tool_call,
            commands::update_companion_settings,
            commands::get_app_paths,
            commands::scan_characters,
            commands::scan_models,
            commands::scan_vrm_models,
            commands::load_settings,
            commands::save_settings,
            commands::save_character_card,
            commands::export_character_card,
            commands::delete_character,
            commands::restore_hidden_characters,
            commands::load_personas,
            commands::save_persona,
            commands::delete_persona,
            commands::create_chat_session,
            commands::list_chat_sessions,
            commands::get_chat_session,
            commands::delete_chat_session,
            commands::rename_chat_session,
            commands::update_chat_author_note,
            commands::get_chat_messages,
            commands::add_chat_message,
            commands::update_chat_message,
            commands::add_message_swipe,
            commands::switch_message_swipe,
            commands::delete_chat_message,
            commands::delete_messages_after,
            commands::export_chat_jsonl,
            commands::import_chat_jsonl,
            commands::fetch_openrouter_models,
            commands::load_llm_presets,
            commands::save_llm_preset,
            commands::delete_llm_preset,
            commands::search_hf_models,
            commands::get_hf_model_files,
            commands::download_gguf_model,
            // Voice / TTS
            commands::list_available_voices,
            commands::synthesize_speech,
            commands::transcribe_speech,
            commands::get_character_voice_config,
            commands::save_character_voice_config,
        ])
        .run(tauri::generate_context!())
        .expect("error while running OtakuSoul application");
}
